### ISSUE TITLE
Hex Drive Flat Head Screws

### ISSUE THREAD

**Issue by STGRobotics** [open-dynamic-robot-initiative/open_robot_actuator_hardware#13]
I counter sink the body_structure_center, body_structure_side. Provides a larger grip surface area. Below are the flat heads I'm using. Would like the step file.

M2.5
https://www.mcmaster.com/91294a022-91294A022

M3
https://www.mcmaster.com/91294a134-91294A134

![Counter Sink](https://user-images.githubusercontent.com/14985729/81846995-f3ccd180-9520-11ea-9f1e-a0d5ffd25830.png)

**Comment by fgrimminger** [comment]
You can find the step files here now...
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/quadruped_robot_12dof_v1/step_files

**Comment by STGRobotics** [comment]
I meet to say, I modified the files and would you like to have them. Regardless thank you for uploading the step files.

**Comment by STGRobotics** [comment]
Replacing metal screw with nylon slotted flat head screws to make bot lighter. Below link is where I purchased from.

https://www.mcmaster.com/plastic-screws/material~plastic/material~nylon-plastic/head-type~flat/thread-type~metric/length~16millimeters/

**Comment by fgrimminger** [comment]
o.k. - thanks - please let us know if this modification works well for you.
