### ISSUE TITLE
reference error, biped leg -> 3dof leg, not 3dof biped leg

### ISSUE THREAD

**Issue by maidenone** [open-dynamic-robot-initiative/open_robot_actuator_hardware#19]
on page:
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/biped_6dof_v1/README.md

section:

Part Name | Quantity | Ordering Information | Comments
-- | -- | -- | --
Biped Leg 3DOF Right Side | 1 | Biped Leg 3DOF Documentation | Custom assembly
Biped Leg 3DOF Left Side | 1 | Biped Leg 3DOF Documentation | Custom assembly

links leads to:
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/leg_3dof_v1/README.md

but it should go to:

https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/biped_leg_3dof_v1

**Comment by fgrimminger** [comment]
Thank you for reporting this. I fixed the links.
Please let us know if you find any other errors.
