### ISSUE TITLE
Motor stand pose angles

### ISSUE THREAD

**Issue by nicrusso7** [open-dynamic-robot-initiative/open_robot_actuator_hardware#26]
Hi there,
this project is awesome! 
I'm trying to simulate the 12DOF model and I was looking for the default motor angles when the robot stands.
Thanks!

**Comment by jviereck** [comment]
Hi, 

they are defined here: https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/master/python/robot_properties_solo/config.py#L182

Closing the issue. Feel free to open it again.

Best,
Julian
