### ISSUE TITLE
Cable routing improvement proposal solo12

### ISSUE THREAD

**Issue by pamartinez-pal** [open-dynamic-robot-initiative/open_robot_actuator_hardware#36]
We are building a solo 12 in pal-robotics and we have found the cable routing around the shoulder joint very complicated. We had some issue with the cables being torn by the consecutive 90º forlds.

The assembly would be much simpler and durable if the cable channel was 3 to 5 mm wider. Would it be possible to expand the "Body Structure Hip AA Support" such that it has more room for the cabling. 

![image](https://user-images.githubusercontent.com/84457488/118825932-65212c00-b8bb-11eb-86b4-45b7c5d88610.png)
![image](https://user-images.githubusercontent.com/84457488/118826719-0314f680-b8bc-11eb-876d-5bddb4b8c0fd.png)

Thank you.

**Comment by fgrimminger** [comment]
True - the internal wire passage is pretty tight.
I increased it by 3mm - from 4mm to 7mm.

You can find the updated STL file [here](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/quadruped_robot_12dof_v1/stl_files/body_structure_hip_aa_support_rev_a.STL).
Does this solve your issue?

![hip_aa_support_comparison_1](https://user-images.githubusercontent.com/53785782/118966265-d91a0d80-b969-11eb-8669-16f4c2827fe2.png)
![hip_aa_support_comparison_2](https://user-images.githubusercontent.com/53785782/118966268-d9b2a400-b969-11eb-838e-5aaa2cdccbf1.png)

Best. Felix

**Comment by pamartinez-pal** [comment]
Great!

Thank you.
