### ISSUE TITLE
Cable Routing improving proposal

### ISSUE THREAD

**Issue by nitrostormbcn** [open-dynamic-robot-initiative/open_robot_actuator_hardware#38]
Hi, I'm Pau from PAL Robotics, we have found some improvement in the part "hip_fe_module_shell" that would greatly improve cable routing. We've had problems assembling the shoulder and this would ease manufacturing without changing the robot's geometry.

Before:
![SoloShoulder](https://user-images.githubusercontent.com/53818995/119972350-6258c200-bfb2-11eb-9692-76a4d9d34fb9.PNG)

After: 
![SoloShoulder_proposal_1](https://user-images.githubusercontent.com/53818995/119972359-65ec4900-bfb2-11eb-8a31-5d33c5d5045d.PNG)

It only modifies the external shell and help routing. I can send you the modified part if you wish.
![SoloShoulder_proposal_2](https://user-images.githubusercontent.com/53818995/119972422-7b617300-bfb2-11eb-8bfc-2f2fe9dadeb4.PNG)
![SoloShoulder_proposal_3](https://user-images.githubusercontent.com/53818995/119972431-7dc3cd00-bfb2-11eb-9ba7-408f89dcdcda.PNG)
![SoloShoulder_proposal_4](https://user-images.githubusercontent.com/53818995/119972434-7ef4fa00-bfb2-11eb-884d-8f3c051325dc.PNG)
![SoloShoulder_proposal_5](https://user-images.githubusercontent.com/53818995/119972436-80262700-bfb2-11eb-86b7-1615482f1206.PNG)

**Comment by fgrimminger** [comment]
Hello Pau,

thanks for your suggestions.

I am surprised to hear that you have so much trouble with the wire routing through the hip.
Are you using the same encoder and motor phase connectors that we are using? ([Details Wiring](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/electronics/details/details_wiring.md#details-wiring))

What kind of wires are you using?
We had bad experiences with ribbon wires.

I first pull the encoder connector and wires through - then the three motor phase wires - one after the other.
Using pliers helps sometimes.

Best. Felix

![wire_routing_hip_1](https://user-images.githubusercontent.com/53785782/119997649-3cdab100-bfd0-11eb-8c83-0a2b886f3977.jpg)

**Comment by nitrostormbcn** [comment]
We've had problems with the cables getting twisted over each other and stripping the insulation, this should be alleviated with looser cable routing. 

Also when replacing the broken wires, disassembly and reassembly was very tedious.

Imho, I think this problems would be solved by allowing more space for the cables to pass.

**Comment by fgrimminger** [comment]
Hi Pau,

o.k. - thanks for your suggestion and the stl file.
I added it to the [3dof leg documentation](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/leg_3dof_v1#3d-printed-parts). 

Best,
Felix

**Comment by dvogureckiy99** [comment]
good afternoon, thanks for the improvement, could you please provide a model in the extension .step or .SLDPRT, not .STL because all sizes are lost in it.
