### ISSUE TITLE
Wrong resistors values

### ISSUE THREAD

**Issue by jochenalt** [open-dynamic-robot-initiative/open_robot_actuator_hardware#40]
Hi all, the schematics of the foot sensor uses a voltage divider via R4/R5, which gives a reference voltage of 2.2V, which is too high for the photosensor used. As a result, the opamp never indicates an illuminated sensor. The voltage divider should rather be something around R4=51K R5=5.1K resulting in a voltage of 0.3V. 
Cheers,
Jochen

**Comment by fgrimminger** [comment]
Hello Jochen,

o.k. - I'm glad to hear that it's working for you.

Good idea - thanks for sharing your modifications.

Best,
Felix
