### ISSUE TITLE
Is the XDS100V3 JTAG a suitable replacement for the XDS100V2?

### ISSUE THREAD

**Issue by kalinkochnev** [open-dynamic-robot-initiative/open_robot_actuator_hardware#41]
The XDS100V2 appears to be discontinued and/or completely out of stock. I looked at the datasheet and V3 appears to support the same specs as V3. I think I'm going to go ahead with the V3, but if someone knows something as to why this can't be used, any suggestions would be appreciated. 

https://www.farnell.com/datasheets/1718777.pdf

**Comment by thomasfla** [comment]
Hello,

I'm not exactly sure about the V3 but I would expect it to work just fine.
Alternatively, we used XDS110 at LAAS with success.

Best, T.

Le ven. 4 mars 2022 à 20:43, Kalin Kochnev ***@***.***> a
écrit :
