### ISSUE TITLE
Missing SOLIDWORKS Parts of quadruped_12dof_v1.1

### ISSUE THREAD

**Issue by acromtech** [open-dynamic-robot-initiative/open_robot_actuator_hardware#43]
Do you have SOLIDWORKS Parts of the quadruped_12dof_v1.1 ?
I need it because I currently work on the Solo head and I only find STL files.
Thanks.

**Comment by fgrimminger** [comment]
Yes - you can find the Solidworks files here now:
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/quadruped_robot_12dof_v1.1/solidworks_files

Best. Felix
