### ISSUE TITLE
Foot Contact Switch connection

### ISSUE THREAD

**Issue by dvogureckiy99** [open-dynamic-robot-initiative/open_robot_actuator_hardware#45]
Hi, how does Foot Contact Switch v1 connect to Micro Driver ?
As I understand it connects to ADC to one of the Micro Driver MCU via U$12 contact.

**Comment by fgrimminger** [comment]
Hi,
each Micro Driver has 2 ADC ports which are evaluated and transmitted at 1kHz.
You want to supply the foot sensor with 3.3V - that's the maximum voltage of the ADCs.
In this schematic the ADC ports are labeled with ADC-A6 and ADC-B6.
![adc_microdriver](https://user-images.githubusercontent.com/53785782/179679658-3a6f3da8-8d5f-47d6-9191-baf0e977b258.png)

**Comment by dvogureckiy99** [comment]
that is, I can connect 2 sensors to one board udriver?

**Comment by fgrimminger** [comment]
Yes - that's possible.
In that case the sensors will have to share the 3.3V and GND connection.
It might be less convenient for assembly and repairs to have both sensors on a single Hirose connector.
It might make sense to connect one sensor per Micro Driver board and use a individual 3pin Hirose connector for each one.

**Comment by dvogureckiy99** [comment]
Thanks!

**Comment by fgrimminger** [comment]
Welcome!
