### ISSUE TITLE
How can I calibrate the Quadruped 12dof (Solo12) ?

### ISSUE THREAD

**Issue by dvogureckiy99** [open-dynamic-robot-initiative/open_robot_actuator_hardware#46]
How can I calibrate the Quadruped 12dof (Solo12) ?

**Comment by fgrimminger** [comment]
We use a calibration tool to find the zero position of the legs.
Do you have that tool?
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/general/robot_calibration.md#calibration-tool-quadruped-12dof
