### ISSUE TITLE
Part weight

### ISSUE THREAD

**Issue by MEE2022** [open-dynamic-robot-initiative/open_robot_actuator_hardware#47]
Do you have any instructions or advice for how to get the correct part weights for 3D resin printing without wasting a ton of time and resin?    How far off can the part weight be (this isn't a very well posed question because it's too general) without the inertia measurement unit and the software failing to perform correctly?

Thank you in advance and thank you for this project.

**Comment by fgrimminger** [comment]
Hi,
don't worry about matching the exact weight of the 3d printed parts in the assembly.
Minor differences in the part weight will have only minimal effect on the inertia and the behavior of the robot.
What's more important are the material properties and the tolerances of the parts.
For the structural parts like the shells we recommend to use a FDM printer like a Fortus or a Ultimaker printer.
The parts from FDM printers are usually cheaper, have shorter print times and and higher impact resistance compared to SLA parts.
For the pulleys the tolerances of the teeth are critical - for those parts we recommend to use a SLA or Multijet printer like a Projet or Formlabs printer. 

Here is some more information: https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/actuator_module_v1/details/details_3d_printed_parts.md#details-3d-printed-parts

Best wishes. Felix
