### ISSUE TITLE
What solidworks version did you use with quadruped_robot_12dof_v1.1

### ISSUE THREAD

**Issue by dvogureckiy99** [open-dynamic-robot-initiative/open_robot_actuator_hardware#51]
Sorry, I cannot open quadruped_robot_12dof_v1.1.
What solidworks version did you use with quadruped_robot_12dof_v1.1 file?

**Comment by fgrimminger** [comment]
Hi, the cad files for the quadruped_robot_12dof_v1.1 were saved with Solidworks 2020.

**Comment by dvogureckiy99** [comment]
Thank you very much, I am already solved this problem by changing my current version to 2022.
