### ISSUE TITLE
Lower leg and Resin Print Questions

### ISSUE THREAD

**Issue by MEE2022** [open-dynamic-robot-initiative/open_robot_actuator_hardware#52]
I'm about to FDM print the lower leg part in carbon fiber.  I see target weights for other parts to make sure the center of mass for the inertia control unit is correct. What infill % did you use to achieve 60g?  Should this be my only carbon fiber part as far as what is strictly necessary?   I would like to resin print the rest.  What is suggested?  What resin would you suggest?  I would like to use my Elegoo Saturn.  Thanks in advance. 

EDIT:  I can't seem to delete this.  I was able to find the information I was looking for
![Untitled](https://user-images.githubusercontent.com/109923951/198753132-314cd1b4-11f4-4b9d-9f86-35577b21356d.jpg)

**Comment by fgrimminger** [comment]
o.k. - I'm glad that you found the information.
No reason to delete your post - we can just close the issue.
Good luck with your project.
