### ISSUE TITLE
Help with the implementation of impedance control

### ISSUE THREAD

**Issue by Seerzy** [open-dynamic-robot-initiative/open_robot_actuator_hardware#53]
Dear experts,

I am currently working on a quadruped robotics project that shares similarities with the open dynamic robots. I would greatly appreciate it if you could provide me with some resources, such as sample code or valuable research papers, to use as a reference for implementing impedance control. Thank you in advance for your assistance.

Tom

**Comment by majidkhadiv** [comment]
Hi,
Implementing impedance control for quadruped robots is quite a simple idea. One of the earliest work implementing it for legged robots is this paper https://journals.sagepub.com/doi/pdf/10.1177/02783640122067309. Same approach was used later on for different robots https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/62121/1/eth-7765-01.pdf and https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8594448 for instance. A similar approach is used for Solo in https://ieeexplore.ieee.org/iel7/7083369/7339444/09015985.pdf but the force distribution problem is solved using quadratic programming. Here you can also find some code for that https://github.com/machines-in-motion/mim_control/tree/main/demos.

Best,
Majid
