### ISSUE TITLE
Electric Schema

### ISSUE THREAD

**Issue by Hadd3s** [open-dynamic-robot-initiative/open_robot_actuator_hardware#59]
Hi, I am reading about your project and soon I hope to start replicating it, could you please provide me with the electrical schematic of the whole project?
Thank you in advance.

**Comment by fgrimminger** [comment]
Hi,
we don't have a detailed electrical schematic of the whole project.
But it's pretty straight-forward: 

- The Master Board and Motor Driver Boards are connected to a 24V power supply.
- Each Motor Driver Board connects to two encoders and two motors.
- The Motor Diver Boards communicate with the Master Board via SPI.
- The Master Board uses a Ethernet connection to communicate with the external control computer.
- The IMU is connected to the Master Board.

You can find more details regarding the wiring here:
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/electronics/details/details_wiring.md#details-wiring

![overview](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/assets/53785782/3ec4aa0c-6389-408c-9d9b-569fefacc903)

Best wishes.
Felix

**Comment by Hadd3s** [comment]
Thanks a lot for taking the time to explain that to me.
