### ISSUE TITLE
AT3 belts?

### ISSUE THREAD

**Issue by AlexDaniel** [open-dynamic-robot-initiative/open_robot_actuator_hardware#8]
Hi! This project is amazing! Finally, a truly open-source dog-like robot.

I'm just curious, what's the justification for using relatively uncommon AT3 belts (instead of let's say GT2). I'm sure you had a good reason, but what is it?

**Comment by fgrimminger** [comment]
Hi - thanks for your interest.
We tested a couple of different timing belts - the main challenge was to prevent tooth skipping under high loads while minimizing friction and backlash.
The Synchroflex AT3 GEN III timing belts consist of polyurethane with steel-cord reinforcements and really tough. Those belts worked well during testing so we settled for them.
The GT2 belts would probably also work fine if you modify the pulley geometry and get the belt tension right.
Best wishes. Felix
