### ISSUE TITLE
Im planning to use this actuator for my 6DOF robotic arm

### ISSUE THREAD

**Issue by stejesh** [open-dynamic-robot-initiative/open_robot_actuator_hardware#9]
Hi,

Is this a good actuator candidate to be used for a robotic arm with 6 degrees of freedom? Im looking for torque, velocity and a bit of position control (not heavily critical ) what kind of repeatability can I expect from this arm and my approx payload

**Comment by fgrimminger** [comment]
Hi,
no - I don't think this is a good candidate for a 6dof arm.
This actuator module was designed for dynamic legged robots.
It's best suited for short high-performance motions and hard impacts.
Handling payloads for longer periods of time will heat up the motors too much.
Also there is no joint sensor on the output - that means the elasticity of the transmission results in end effector position errors. We have not measured the positioning repeatability.
We are using the actuator module for a 3 finger hand: https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/tri_finger_edu_v1/README.md#trifingeredu-v1
But for a 6dof arm you'll need higher gear ratios or stronger motors for the shoulder actuators.
This would require redesigning a lot of the mechanics.
